"""add attendance tables (employees, attendance_records, leave_records, inactive_periods, public_holidays, special_days)

Revision ID: 892920152190
Revises: 56f2f7587ef7
Create Date: 2026-05-26 12:10:51.490374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892920152190'
down_revision: Union[str, Sequence[str], None] = '56f2f7587ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Text(), nullable=True),
    sa.Column('active', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('public_holidays',
    sa.Column('holiday_date', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_paid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('holiday_date')
    )
    op.create_table('special_days',
    sa.Column('special_date', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('special_date')
    )
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('work_date', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Text(), nullable=True),
    sa.Column('end_time', sa.Text(), nullable=True),
    sa.Column('work_hours', sa.Float(), nullable=True),
    sa.Column('day_fraction', sa.Float(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'work_date')
    )
    op.create_index('idx_attendance_date', 'attendance_records', ['work_date'], unique=False)
    op.create_index('idx_attendance_emp_month', 'attendance_records', ['employee_id', 'work_date'], unique=False)
    op.create_table('inactive_periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inactive_emp', 'inactive_periods', ['employee_id'], unique=False)
    op.create_table('leave_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('employee_id', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('end_date', sa.Text(), nullable=True),
    sa.Column('leave_type', sa.Text(), server_default='full', nullable=False),
    sa.Column('hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_leave_date', 'leave_records', ['start_date'], unique=False)
    op.create_index('idx_leave_emp', 'leave_records', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leave_emp', table_name='leave_records')
    op.drop_index('idx_leave_date', table_name='leave_records')
    op.drop_table('leave_records')
    op.drop_index('idx_inactive_emp', table_name='inactive_periods')
    op.drop_table('inactive_periods')
    op.drop_index('idx_attendance_emp_month', table_name='attendance_records')
    op.drop_index('idx_attendance_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_table('special_days')
    op.drop_table('public_holidays')
    op.drop_table('employees')
    # ### end Alembic commands ###
