"""add purchase_orders and purchase_order_lines tables

Revision ID: cb40fb302571
Revises: 892920152190
Create Date: 2026-05-26 13:21:09.026136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb40fb302571'
down_revision: Union[str, Sequence[str], None] = '892920152190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('supplier_id', sa.Text(), nullable=True),
    sa.Column('order_date', sa.Text(), nullable=False),
    sa.Column('arrival_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='placed', nullable=False),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('total_qty', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_po_order_date', 'purchase_orders', ['order_date'], unique=False)
    op.create_index('idx_po_supplier', 'purchase_orders', ['supplier_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_barcode', sa.Text(), nullable=False),
    sa.Column('qty_ordered', sa.Integer(), nullable=False),
    sa.Column('qty_arrived', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pol_barcode', 'purchase_order_lines', ['product_barcode'], unique=False)
    op.create_index('idx_pol_order', 'purchase_order_lines', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_pol_order', table_name='purchase_order_lines')
    op.drop_index('idx_pol_barcode', table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index('idx_po_supplier', table_name='purchase_orders')
    op.drop_index('idx_po_order_date', table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###
